"use client";

import { useParams } from "next/navigation";
import { useState } from "react";

const tabs=["홈","영상","클립","LIVE","재생목록","정보"];
export default function ChannelPage(){
 const params=useParams<{handle:string}>(); const handle=params?.handle||"dguy"; const [tab,setTab]=useState("홈"); const [follow,setFollow]=useState(false); const [bell,setBell]=useState("전체");
 return <main className="pf-shell"><div className="pf-wrap"><div className="pf-cover"/><section className="pf-card" style={{marginTop:-44,position:"relative"}}><div className="pf-between"><div className="pf-row"><div className="pf-avatar" style={{width:82,height:82,fontSize:28}}>D</div><div><span className="pf-kicker">DTV CHANNEL</span><h1 className="pf-title" style={{fontSize:32}}>드가이 스포츠</h1><p className="pf-sub">@{handle} · 구독자 12.8만 · 영상 184개</p></div></div><div className="pf-actions"><button className={`pf-btn ${follow?"":"primary"}`} onClick={()=>setFollow(v=>!v)}>{follow?"주파수 저장됨 ✓":"주파수 저장"}</button><select className="pf-btn" value={bell} onChange={e=>setBell(e.target.value)}><option>전체 알림</option><option>맞춤 알림</option><option>알림 없음</option></select><button className="pf-btn">↗ 공유</button></div></div><div className="pf-tabs" style={{marginTop:18,marginBottom:0}}>{tabs.map(x=><button key={x} className={`pf-tab ${tab===x?"active":""}`} onClick={()=>setTab(x)}>{x}</button>)}</div></section>
 <div style={{height:14}}/>
 {tab==="홈"&&<div className="pf-grid"><section className="pf-card pf-span8"><span className="pf-kicker">FEATURED BROADCAST</span><div className="pf-player" style={{marginTop:10}}><span className="pf-playicon">⚾</span></div><h2 style={{marginTop:12}}>이번 주 대표 방송</h2><p>한화 경기 흐름 같이 보기 · 조회수 12만</p><a className="pf-btn primary" href="/watch/1">재생</a></section><aside className="pf-card pf-span4"><h2>채널 정보</h2><p>야구, 스포츠, 가끔 코딩. DTV에서 켜지는 개인 방송국.</p><div className="pf-divider"/><div className="pf-stack"><div className="pf-between"><span>총 조회수</span><b>18.4M</b></div><div className="pf-between"><span>가입일</span><b>2026</b></div><div className="pf-between"><span>콘텐츠 등급</span><b>전체/12+</b></div></div></aside></div>}
 {tab==="영상"&&<div className="pf-grid">{["⚾","⌨","D","👁","♫","✎"].map((icon,i)=><article className="pf-card pf-span4" key={i}><div className="pf-thumb" style={{height:150,fontSize:45}}>{icon}</div><h3 style={{marginTop:12}}>채널 영상 #{i+1}</h3><p>{i+2}.4만회 · {i+1}일 전</p><a className="pf-btn" href={`/watch/${i+1}`}>보기</a></article>)}</div>}
 {tab==="클립"&&<section className="pf-card"><div className="pf-between"><h2>짧은 신호</h2><a className="pf-btn primary" href="/clips">클립 피드 열기</a></div><p>세로형, 정사각형, 가로형 등 원본 비율을 유지하는 DTV 클립.</p></section>}
 {tab==="LIVE"&&<section className="pf-card"><div className="pf-between"><div><span className="pf-status good">ON AIR</span><h2 style={{marginTop:10}}>오늘 경기 같이 보기</h2><p>1.2K명 시청 중 · 라이브 채팅 활성</p></div><a className="pf-btn red" href="/watch/101">LIVE 입장</a></div></section>}
 {tab==="재생목록"&&<div className="pf-grid">{[["경기 같이보기","22개"],["야구 이슈","34개"],["DTV 제작기","12개"]].map(x=><article className="pf-card pf-span4" key={x[0]}><div className="pf-thumb" style={{height:120}}>▤</div><h2 style={{marginTop:12}}>{x[0]}</h2><p>{x[1]} · 공개</p><button className="pf-btn">열기</button></article>)}</div>}
 {tab==="정보"&&<section className="pf-card"><h2>채널 소개</h2><p>이 채널은 스포츠와 제작 콘텐츠를 중심으로 방송합니다. 채널 운영자가 지정한 기본 콘텐츠 등급은 전체 이용가이며 일부 LIVE/영상은 별도 등급이 적용될 수 있습니다.</p><div className="pf-divider"/><div className="pf-actions"><button className="pf-btn">채널 공유</button><button className="pf-btn">채널 신고</button><button className="pf-btn danger">채널 차단</button></div></section>}
 </div></main>
}
