"use client";

import { useState } from "react";

export default function AccountPage(){
 const [signed,setSigned]=useState(true); const [name,setName]=useState("드가이"); const [handle,setHandle]=useState("@dguy"); const [saved,setSaved]=useState(false);
 return <main className="pf-shell"><div className="pf-wrap"><header className="pf-head"><div><span className="pf-kicker">DTV ACCOUNT</span><h1 className="pf-title">계정 · 프로필</h1><p className="pf-sub">로그인 상태, 프로필, 채널 기본 정보와 계정 연결 상태를 관리합니다.</p></div><a className="pf-btn" href="/settings">설정</a></header>
 {!signed?<section className="pf-card" style={{maxWidth:520,margin:"80px auto"}}><h2>DTV에 로그인</h2><p>시청 기록, 보관함, 채널 구독과 업로드 기능을 사용하려면 로그인하세요.</p><div className="pf-stack"><button className="pf-btn primary" onClick={()=>setSigned(true)}>Google로 계속</button><button className="pf-btn" onClick={()=>setSigned(true)}>이메일로 계속</button></div></section>:<div className="pf-grid"><section className="pf-card pf-span7"><div className="pf-row"><div className="pf-avatar" style={{width:72,height:72,fontSize:22}}>D</div><div><h2>{name}</h2><p>{handle} · DTV 채널 운영자</p></div></div><div className="pf-divider"/><div className="pf-formgrid"><div className="pf-field"><label>표시 이름</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="pf-field"><label>핸들</label><input value={handle} onChange={e=>setHandle(e.target.value)}/></div><div className="pf-field"><label>소개</label><input defaultValue="영상과 방송을 만드는 중 📡"/></div><div className="pf-field"><label>연락 이메일</label><input defaultValue="creator@example.com"/></div></div><button className="pf-btn primary" style={{marginTop:14}} onClick={()=>setSaved(true)}>{saved?"저장됨 ✓":"프로필 저장"}</button></section><aside className="pf-card pf-span5"><h2>계정 상태</h2><div className="pf-stack" style={{marginTop:14}}><div className="pf-between"><span>로그인</span><span className="pf-status good">연결됨</span></div><div className="pf-between"><span>채널</span><b>{handle}</b></div><div className="pf-between"><span>2단계 인증</span><span className="pf-status wait">권장</span></div><div className="pf-between"><span>업로드 권한</span><span className="pf-status good">사용 가능</span></div></div><div className="pf-divider"/><button className="pf-btn danger" onClick={()=>setSigned(false)}>로그아웃</button></aside></div>}
 </div></main>
}
