"use client";

import { useState } from "react";

export default function SettingsPage(){
 const [notice,setNotice]=useState({upload:true,live:true,reply:true,channel:true,marketing:false}); const [restricted,setRestricted]=useState(true); const [autoplay,setAutoplay]=useState(true); const [quality,setQuality]=useState("자동");
 const toggle=(k:keyof typeof notice)=>setNotice(v=>({...v,[k]:!v[k]}));
 return <main className="pf-shell"><div className="pf-wrap"><header className="pf-head"><div><span className="pf-kicker">DTV SETTINGS</span><h1 className="pf-title">설정</h1><p className="pf-sub">알림, 재생 기본값, 개인정보, 콘텐츠 등급과 추천 환경을 조정합니다.</p></div><a className="pf-btn" href="/account">계정</a></header><div className="pf-grid">
 <section className="pf-card pf-span6"><h2>알림 세분화</h2><p>필요한 신호만 받도록 종류별로 켜고 끌 수 있습니다.</p><div className="pf-stack">{[["upload","구독 채널 새 영상"],["live","LIVE 시작"],["reply","내 댓글 답글"],["channel","채널 공지"],["marketing","DTV 추천/프로모션"]].map(([k,label])=><label className="pf-between" key={k}><span>{label}</span><span className="pf-toggle"><input type="checkbox" checked={notice[k as keyof typeof notice]} onChange={()=>toggle(k as keyof typeof notice)}/></span></label>)}</div></section>
 <section className="pf-card pf-span6"><h2>재생 기본값</h2><div className="pf-formgrid" style={{marginTop:12}}><div className="pf-field"><label>기본 화질</label><select value={quality} onChange={e=>setQuality(e.target.value)}><option>자동</option><option>1080p</option><option>720p</option><option>480p</option></select></div><div className="pf-field"><label>기본 배속</label><select><option>1x</option><option>1.25x</option><option>1.5x</option><option>2x</option></select></div></div><div className="pf-divider"/><label className="pf-between"><span>다음 영상 자동 재생</span><span className="pf-toggle"><input type="checkbox" checked={autoplay} onChange={()=>setAutoplay(v=>!v)}/></span></label><label className="pf-between" style={{marginTop:12}}><span>자막 자동 표시</span><span className="pf-toggle"><input type="checkbox" defaultChecked/></span></label></section>
 <section className="pf-card pf-span6"><h2>콘텐츠 · 연령 설정</h2><p>민감하거나 연령 제한이 있는 콘텐츠 노출 방식을 설정합니다.</p><label className="pf-between"><span>제한 모드</span><span className="pf-toggle"><input type="checkbox" checked={restricted} onChange={()=>setRestricted(v=>!v)}/></span></label><div className="pf-field" style={{marginTop:12}}><label>허용 콘텐츠 등급</label><select><option>전체 이용가</option><option>12세 이상까지</option><option>15세 이상까지</option></select></div><p className="pf-note">계정 연령 및 보호자 설정이 있는 경우 일부 옵션은 자동으로 제한될 수 있습니다.</p></section>
 <section className="pf-card pf-span6"><h2>개인정보 · 추천</h2><div className="pf-stack"><label className="pf-between"><span>시청 기록으로 추천 개선</span><span className="pf-toggle"><input type="checkbox" defaultChecked/></span></label><label className="pf-between"><span>검색 기록 저장</span><span className="pf-toggle"><input type="checkbox" defaultChecked/></span></label><label className="pf-between"><span>구독 목록 공개</span><span className="pf-toggle"><input type="checkbox"/></span></label></div><div className="pf-divider"/><div className="pf-actions"><button className="pf-btn">추천 데이터 초기화</button><button className="pf-btn danger">시청 기록 삭제</button></div></section>
 </div></div></main>
}
